
###
# Authentification du client
POST http://localhost:81/auth/connect
content-type: application/json

{
    "email" : "client1@mail.com",
    "password" : "password"
}

###
# CRÉER Client
POST http://localhost:81/client/register
content-type: application/json

{
    "email": "client7@mail.com",
    "password":"password",
    "lastname" : "NomCli7",
    "firstname" : "PrenomCli7",
    "photo" : null,
    "gender":"FEMALE",
    "birthdate" : "2002-04-11",
    "phone" : "0611111111",
    "address" : "15RueBouret",
    "city" : "Paris",
    "zipcode" : "75019",
    "here_for" : "ALL",
    "intrested_by" : "MALE"
}




###
# LIST COMMUNITY by CLIENTID
GET http://localhost:3001/community/getCommunityByClientId
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNsaWVudDFAbWFpbC5jb20iLCJpYXQiOjE2NzA2MjQ0ODgsImV4cCI6MTY3MDcxMDg4OH0.SzPjpxl_5EY9nnnwTlJMmh_uQ1VSHT3_4fCILrZ0p7k
content-type: application/json

{
    "client_id" : 20
}

###
# ADD CLIENT TO COMMUNITY
POST http://localhost:81/community/addClientToCommunity
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNsaWVudDFAbWFpbC5jb20iLCJpYXQiOjE2NzA2MjQ0ODgsImV4cCI6MTY3MDcxMDg4OH0.SzPjpxl_5EY9nnnwTlJMmh_uQ1VSHT3_4fCILrZ0p7k
content-type: application/json

{
    "pro_id" : 1,
    "client_id" : 22
}

###
# FIRE CLIENT FROM COMMUNITY
POST http://localhost:81/community/fireClientFromCommunity
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNsaWVudDFAbWFpbC5jb20iLCJpYXQiOjE2NzA2MjQ0ODgsImV4cCI6MTY3MDcxMDg4OH0.SzPjpxl_5EY9nnnwTlJMmh_uQ1VSHT3_4fCILrZ0p7k
content-type: application/json

{
    "community_id" : 1
}

###
# LEAVE A COMMUNITY
POST http://localhost:81/community/leaveCommunity
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNsaWVudDFAbWFpbC5jb20iLCJpYXQiOjE2NzA0NTI5NzUsImV4cCI6MTY3MDUzOTM3NX0.eXoLTqw-p1LgI5AiPzJfqLs1HSDH0GIwEZ6ptvftD7A
content-type: application/json

{
    "community_id" : 18
}

###
# GET COMMUNITY BY CLIENT ID
GET http://localhost:3001/community/getCommunitiesByClientId
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNsaWVudDFAbWFpbC5jb20iLCJpYXQiOjE2NzA2MjQ0ODgsImV4cCI6MTY3MDcxMDg4OH0.SzPjpxl_5EY9nnnwTlJMmh_uQ1VSHT3_4fCILrZ0p7k
content-type: application/json

{
    "client_id" : 20
}

###
# GET MEMBERS OF A COMMUNITY BY PRO ID
GET http://localhost:3001/community/getCommunitiyMembersByProId
content-type: application/json

{
    "pro_id" : 1
}

###
# CRÉER PASSION
POST http://localhost:3001/passions/
content-type: application/json

{
    "passion_name" : "Sport"
}

###
# CRÉER User
POST http://localhost:3001/user/register
content-type: application/json

{
    "email" : "pro@mail.com",
    "password" : "password",
    "role" : "client"
}

###
# LOGIN User
POST http://localhost:3001/user/login
content-type: application/json

{
    "email" : "pro@mail.com",
    "password" : "password"
}



###
# CRÉER Match
POST http://localhost:3001/matchs/create
content-type: application/json

{
    "client1_id" : 1,
    "client2_id" : 2,
    "pro_id" : 1
}

###
# LIRE Client
POST http://localhost:81/client/getClientById
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNsaWVudDFAbWFpbC5jb20iLCJpYXQiOjE2NzAyNzc1NjQsImV4cCI6MTY3MDM2Mzk2NH0.xEJtoDUOdwShCT0zVf75OWJaE3jUsX85yhwXnBba4hI
content-type: application/json

{
    "id_client" : 19
}


###
# LIST Propositions de Match
GET http://localhost:81/propositions/proposition
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNsaWVudDFAbWFpbC5jb20iLCJpYXQiOjE2NzAyNzc1NjQsImV4cCI6MTY3MDM2Mzk2NH0.xEJtoDUOdwShCT0zVf75OWJaE3jUsX85yhwXnBba4hI
content-type: application/json

{
    "pro_id" : 1
}

###
# LIST Pro
POST http://localhost:81/pro/getAllPro
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNsaWVudDFAbWFpbC5jb20iLCJpYXQiOjE2NzAyNzc1NjQsImV4cCI6MTY3MDM2Mzk2NH0.xEJtoDUOdwShCT0zVf75OWJaE3jUsX85yhwXnBba4hI


###
# LIST Propositions de Match
GET http://localhost:3001/matchs2/propositions
content-type: application/json

{
    "client_id" : 1,
    "pro_id" : 1
}

###
# LIST Propositions de Match
POST http://localhost:3001/client/getClientById/1
content-type: application/json

{
    "client_id" : 1,
    "pro_id" : 1
}

###
# GET Ratings by Pro
GET http://localhost:3001/rating/rateByPro/
content-type: application/json

{
    "pro_id" : 1
}

###
# POST Auth
POST http://localhost:3001/client/authenticate
content-type: application/json

{
    "client_email" : "test",
    "client_password" : "password"
}

###
# LIRE Toutes les communaute
GET http://localhost:81/community/getAllCommunities
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNsaWVudDFAbWFpbC5jb20iLCJpYXQiOjE2NzAyNzc1NjQsImV4cCI6MTY3MDM2Mzk2NH0.xEJtoDUOdwShCT0zVf75OWJaE3jUsX85yhwXnBba4hI
content-type: application/json

###
# LIRE communaute by client id
GET http://localhost:81/community/getCommunityByClientId
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNsaWVudDFAbWFpbC5jb20iLCJpYXQiOjE2NzAyNzc1NjQsImV4cCI6MTY3MDM2Mzk2NH0.xEJtoDUOdwShCT0zVf75OWJaE3jUsX85yhwXnBba4hI
content-type: application/json

{
    "client_id" : 18
}

###
# GET pro by id
POST http://localhost:81/pro/getProById
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNsaWVudDFAbWFpbC5jb20iLCJpYXQiOjE2NzAyNzc1NjQsImV4cCI6MTY3MDM2Mzk2NH0.xEJtoDUOdwShCT0zVf75OWJaE3jUsX85yhwXnBba4hI
content-type: application/json

{
    "pro_id" : 2
}

###
# GET community's members by pro id
POST http://localhost:81/community/getCommunitiyMembers
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNsaWVudDFAbWFpbC5jb20iLCJpYXQiOjE2NzAyNzc1NjQsImV4cCI6MTY3MDM2Mzk2NH0.xEJtoDUOdwShCT0zVf75OWJaE3jUsX85yhwXnBba4hI
content-type: application/json

{
    "pro_id" : 1
}