
###
# Authentification du client
POST http://localhost:81/auth/connect
content-type: application/json

{
    "email" : "client1@mail.com",
    "password" : "password"
}

###
# CRÉER Client
POST http://localhost:3001/client/register
content-type: application/json

{
    "email": "client1@mail.com",
    "password":"password",
    "lastname" : "NomCli1",
    "firstname" : "PrenomCli1",
    "photo" : null,
    "gender":"F",
    "birthdate" : "11/04/2003",
    "phone" : "0654345434",
    "address" : "24 Rue Bouret",
    "city" : "Paris",
    "zipcode" : "75019",
    "here_for" : "both",
    "intrested_by" : "M"
}




###
# LIST COMMUNITY by CLIENTID
GET http://localhost:3001/community/getCommunityByClientId
content-type: application/json

{
    "client_id" : 20
}

###
# ADD CLIENT TO COMMUNITY
POST http://localhost:3001/community/addClientToCommunity
content-type: application/json

{
    "pro_id" : 1,
    "client_id" : 20
}

###
# FIRE CLIENT FROM COMMUNITY
POST http://localhost:3001/community/fireClientFromCommunity
content-type: application/json

{
    "pro_id" : 1,
    "client_id" : 20
}

###
# LEAVE A COMMUNITY
POST http://localhost:3001/community/leaveCommunity
content-type: application/json

{
    "pro_id" : 1,
    "client_id" : 20
}

###
# GET COMMUNITY BY CLIENT ID
GET http://localhost:3001/community/getCommunitiesByClientId
content-type: application/json

{
    "client_id" : 20
}

###
# GET MEMBERS OF A COMMUNITY BY PRO ID
GET http://localhost:3001/community/getCommunitiyMembersByProId
content-type: application/json

{
    "pro_id" : 1
}

###
# CRÉER PASSION
POST http://localhost:3001/passions/
content-type: application/json

{
    "passion_name" : "Sport"
}

###
# CRÉER User
POST http://localhost:3001/user/register
content-type: application/json

{
    "email" : "pro@mail.com",
    "password" : "password",
    "role" : "client"
}

###
# LOGIN User
POST http://localhost:3001/user/login
content-type: application/json

{
    "email" : "pro@mail.com",
    "password" : "password"
}



###
# CRÉER Match
POST http://localhost:3001/matchs/create
content-type: application/json

{
    "client1_id" : 1,
    "client2_id" : 2,
    "pro_id" : 1
}

###
# LIRE Client
POST http://localhost:81/client/getClientById
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNsaWVudDFAbWFpbC5jb20iLCJpYXQiOjE2NjI4NjM4NDAsImV4cCI6MTY2Mjk1MDI0MH0.u4DXIuD9ws18tQGze71KAFeoXARM4GNc3PHVgjofC9E
content-type: application/json

{
    "id_client" : 19
}


###
# LIST Propositions de Match
GET http://localhost:81/matchs/propositions
content-type: application/json

{
    "client_id" : 1,
    "pro_id" : 1
}

###
# LIST Propositions de Match
GET http://localhost:3001/matchs2/propositions
content-type: application/json

{
    "client_id" : 1,
    "pro_id" : 1
}

###
# LIST Propositions de Match
POST http://localhost:3001/client/getClientById/1
content-type: application/json

{
    "client_id" : 1,
    "pro_id" : 1
}

###
# GET Ratings by Pro
GET http://localhost:3001/rating/rateByPro/
content-type: application/json

{
    "pro_id" : 1
}

###
# POST Auth
POST http://localhost:3001/client/authenticate
content-type: application/json

{
    "client_email" : "test",
    "client_password" : "password"
}