
###
# Authentification du client
POST http://localhost:3001/client/authenticate
content-type: application/json

{
    "client_email" : "test@test.fr",
    "client_password" : "test"
}

###
# CRÉER Client
POST http://localhost:3001/client/register
content-type: application/json

{
    "email": "client1@mail.com",
    "password":"password",
    "lastname" : "NomCli1",
    "firstname" : "PrenomCli1",
    "photo" : null,
    "gender":"F",
    "birthdate" : "11/04/2003",
    "phone" : "0654345434",
    "address" : "24 Rue Bouret",
    "city" : "Paris",
    "zipcode" : "75019",
    "here_for" : "both",
    "intrested_by" : "M"
}




###
# LIST PASSIONS
GET http://localhost:3001/passions/

###
# CRÉER PASSION
POST http://localhost:3001/passions/
content-type: application/json

{
    "passion_name" : "Sport"
}

###
# CRÉER User
POST http://localhost:3001/user/register
content-type: application/json

{
    "email" : "pro@mail.com",
    "password" : "password",
    "role" : "client"
}

###
# LOGIN User
POST http://localhost:3001/user/login
content-type: application/json

{
    "email" : "pro@mail.com",
    "password" : "password"
}



###
# CRÉER Match
POST http://localhost:3001/matchs/create
content-type: application/json

{
    "client1_id" : 1,
    "client2_id" : 2,
    "pro_id" : 1
}

###
# LIRE Client
GET http://localhost:3001/client/clientById/1


###
# LIST Propositions de Match
GET http://localhost:3001/matchs/propositions
content-type: application/json

{
    "client_id" : 1,
    "pro_id" : 1
}

###
# LIST Propositions de Match
GET http://localhost:3001/matchs2/propositions
content-type: application/json

{
    "client_id" : 1,
    "pro_id" : 1
}

###
# LIST Propositions de Match
POST http://localhost:3001/client/getClientById/1
content-type: application/json

{
    "client_id" : 1,
    "pro_id" : 1
}

###
# GET Ratings by Pro
GET http://localhost:3001/rating/rateByPro/
content-type: application/json

{
    "pro_id" : 1
}

###
# POST Auth
POST http://localhost:3001/client/authenticate
content-type: application/json

{
    "client_email" : "test",
    "client_password" : "password"
}